name: workout_planner
description: A workout plan application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+12

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  confetti: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.0-nullsafety.0
  sqflite: ^3.0.0-nullsafety.0
  path_provider: ^2.0.0-nullsafety.0
  charts_flutter: ^1.1.0-nullsafety.0
  qr_flutter: ^3.0.0-nullsafety.0
  qrcode_reader: ^1.0.0-nullsafety.0
  shared_preferences: ^3.0.0-nullsafety.0
  package_info: ^1.0.0-nullsafety.0
  google_sign_in: ^5.0.0-nullsafety.0
  percent_indicator: ^2.0.0-nullsafety.0
  cloud_firestore: ^2.0.0-nullsafety.0
  connectivity: ^2.0.0-nullsafety.0
  rxdart: ^1.0.0-nullsafety.0
  image_gallery_saver: ^2.0.0-nullsafety.0
  permission_handler: ^4.0.0-nullsafety.0
  share: ^2.0.0-nullsafety.0
  firebase_auth: ^3.0.0-nullsafety.0
  uuid: ^3.0.0-nullsafety.0
  app_review: ^2.0.0-nullsafety.0
  apple_sign_in: ^1.0.0-nullsafety.0
  font_awesome_flutter: ^9.0.0-nullsafety.0
  flutter_signin_button: 2.0.0
  keyboard_actions: ^4.2.0

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
  - assets/test.jpg
  - assets/dumbbells.png
  - assets/stopwatch.png
  - assets/dumbbell-48.png
  - assets/dumbbell-96.png
  - assets/chest-96.png
  - assets/muscle-96.png
  - assets/back-96.png
  - assets/leg-96.png
  - assets/abs-96.png
  - database/data.db
  - assets/ic_launcher.png
  - assets/app_icon.png

  fonts:
  - family: Petit
    fonts:
    - asset: fonts/PetitFormalScript-Regular.ttf
  - family: Roboto
    fonts:
    - asset: fonts/Roboto-Regular.ttf
    - asset: fonts/Roboto-Light.ttf
    - asset: fonts/Roboto-Thin.ttf
    - asset: fonts/Roboto-Bold.ttf
  - family: Staa
    fonts:
    - asset: fonts/Staatliches-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
